import React, { useState } from 'react';
import { ResearchReport } from '../types';
import { generateResearchReport } from '../services/reportService';
import { checkAndIncrementUsage } from '../services/usageService';
import { 
  Search, 
  BookOpen, 
  MapPin, 
  Thermometer, 
  Wind, 
  ExternalLink,
  Loader2,
  FileText,
  Image as ImageIcon,
  FlaskConical,
  Download
} from 'lucide-react';

const ReportPage: React.FC = () => {
  const [topic, setTopic] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [report, setReport] = useState<ResearchReport | null>(null);

  const handleSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!topic.trim()) return;
    if (!checkAndIncrementUsage()) return;

    setIsLoading(true);
    setReport(null);
    try {
      const data = await generateResearchReport(topic);
      setReport(data);
    } catch (error) {
      console.error("Report generation failed", error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleDownload = () => {
    if (!report) return;
    
    // Create Markdown Content
    const content = `
# ${report.topic}
Generated by Captain's Research Lab on ${new Date(report.timestamp).toLocaleString()}

${report.content}

---
Sources:
${report.sources.map(s => `- ${s.title}: ${s.url}`).join('\n')}
    `;

    const element = document.createElement("a");
    const file = new Blob([content], {type: 'text/markdown'});
    element.href = URL.createObjectURL(file);
    element.download = `${report.topic.replace(/\s+/g, '_').toLowerCase()}_report.md`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="flex flex-col h-full bg-[#0f172a] overflow-hidden">
      {/* Search Header */}
      <div className="bg-[#1e293b] border-b border-slate-700/50 p-6 shadow-lg z-10">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-2xl font-bold text-white mb-2 flex items-center gap-2">
            <FlaskConical className="w-6 h-6 text-cyan-400" />
            Research Lab
          </h2>
          <p className="text-slate-400 text-sm mb-6">
            Access real-time intelligence, published literature, and AI-generated analysis for any oceanographic topic.
          </p>
          
          <form onSubmit={handleSearch} className="relative">
            <input
              type="text"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="Enter research topic (e.g., 'Coral Bleaching in the Great Barrier Reef', 'Deep Sea Hydrothermal Vents')..."
              className="w-full bg-[#0f172a] border border-slate-600 rounded-xl py-4 pl-12 pr-4 text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent shadow-inner transition-all"
            />
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-500" />
            <button 
              type="submit"
              disabled={isLoading || !topic}
              className="absolute right-2 top-1/2 -translate-y-1/2 bg-cyan-600 hover:bg-cyan-500 disabled:bg-slate-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors"
            >
              {isLoading ? 'Analyzing...' : 'Generate Report'}
            </button>
          </form>
        </div>
      </div>

      {/* Content Area */}
      <div className="flex-1 overflow-y-auto p-4 md:p-8">
        <div className="max-w-4xl mx-auto">
          
          {isLoading && (
            <div className="flex flex-col items-center justify-center py-20 text-slate-500 space-y-4">
              <Loader2 className="w-12 h-12 animate-spin text-cyan-400" />
              <p className="animate-pulse">Scanning global databases & satellite telemetry...</p>
            </div>
          )}

          {!isLoading && !report && (
            <div className="text-center py-20 text-slate-600">
              <BookOpen className="w-16 h-16 mx-auto mb-4 opacity-20" />
              <p>Enter a topic above to begin research.</p>
            </div>
          )}

          {report && (
            <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
              
              {/* Title Header */}
              <div className="border-b border-slate-700 pb-6 flex items-start justify-between">
                <div>
                    <h1 className="text-3xl md:text-4xl font-bold text-white mb-2 capitalize">{report.topic}</h1>
                    <div className="flex items-center gap-4 text-sm text-slate-400">
                    <span>Generated: {new Date(report.timestamp).toLocaleString()}</span>
                    <span className="w-1 h-1 bg-slate-600 rounded-full"></span>
                    <span className="text-cyan-400">AI Verified</span>
                    </div>
                </div>
                <button 
                  onClick={handleDownload}
                  className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-white rounded-lg transition-colors border border-slate-700 shadow-lg"
                >
                    <Download className="w-4 h-4" />
                    Download Report
                </button>
              </div>

              {/* Top Section: Visuals & Real-time Data Grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                
                {/* Generated Visual */}
                {report.generatedImage && (
                  <div className="bg-[#1e293b] rounded-2xl border border-slate-700 overflow-hidden shadow-xl">
                    <div className="p-4 border-b border-slate-700 bg-slate-800/50 flex items-center gap-2">
                       <ImageIcon className="w-4 h-4 text-indigo-400" />
                       <span className="text-xs font-bold text-slate-300 uppercase tracking-wider">AI Visualization</span>
                    </div>
                    <div className="relative group">
                       <img 
                         src={report.generatedImage.url} 
                         alt="AI Generated" 
                         className="w-full h-64 object-cover"
                       />
                       <div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent opacity-0 group-hover:opacity-100 transition-opacity p-4 flex items-end">
                          <p className="text-xs text-white">{report.generatedImage.prompt}</p>
                       </div>
                    </div>
                  </div>
                )}

                {/* Real-time Context */}
                {report.locationContext ? (
                  <div className="bg-[#1e293b] rounded-2xl border border-slate-700 overflow-hidden shadow-xl flex flex-col">
                    <div className="p-4 border-b border-slate-700 bg-slate-800/50 flex items-center justify-between">
                       <div className="flex items-center gap-2">
                          <MapPin className="w-4 h-4 text-emerald-400" />
                          <span className="text-xs font-bold text-slate-300 uppercase tracking-wider">Live Conditions</span>
                       </div>
                       <span className="text-xs text-slate-400">{report.locationContext.name}</span>
                    </div>
                    
                    <div className="p-6 flex-1 flex flex-col justify-center gap-6">
                       <div className="flex items-center justify-between">
                          <div className="flex items-center gap-3">
                             <div className="p-3 bg-slate-800 rounded-full text-cyan-400">
                                <Thermometer className="w-6 h-6" />
                             </div>
                             <div>
                                <p className="text-sm text-slate-400">Air Temp</p>
                                <p className="text-2xl font-bold text-white">
                                  {report.locationContext.weather.current.temperature_2m}°C
                                </p>
                             </div>
                          </div>
                          <div className="text-right">
                             <p className="text-sm text-slate-400">Water Surface (Est)</p>
                             <p className="text-xl font-semibold text-slate-200">
                               {(report.locationContext.weather.current.temperature_2m * 0.9).toFixed(1)}°C
                             </p>
                          </div>
                       </div>

                       <div className="flex items-center justify-between">
                          <div className="flex items-center gap-3">
                             <div className="p-3 bg-slate-800 rounded-full text-teal-400">
                                <Wind className="w-6 h-6" />
                             </div>
                             <div>
                                <p className="text-sm text-slate-400">Wind Speed</p>
                                <p className="text-2xl font-bold text-white">
                                  {report.locationContext.weather.current.wind_speed_10m} <span className="text-sm text-slate-500">km/h</span>
                                </p>
                             </div>
                          </div>
                          <div className="text-right">
                             <p className="text-sm text-slate-400">Direction</p>
                             <p className="text-xl font-semibold text-slate-200">
                               {report.locationContext.weather.current.wind_direction_10m}°
                             </p>
                          </div>
                       </div>
                    </div>
                  </div>
                ) : (
                  <div className="bg-[#1e293b]/50 rounded-2xl border border-slate-700/50 p-6 flex flex-col items-center justify-center text-center text-slate-500">
                     <MapPin className="w-8 h-8 mb-2 opacity-50" />
                     <p className="text-sm">No specific geographic coordinates identified for this topic.</p>
                  </div>
                )}
              </div>

              {/* Main Report Body */}
              <div className="bg-[#1e293b] border border-slate-700 rounded-2xl p-6 md:p-8 shadow-xl">
                 <div className="prose prose-invert prose-base md:prose-lg max-w-none">
                    {/* Simple formatting for markdown-like text */}
                    {report.content.split('\n').map((line, i) => {
                       if (line.startsWith('# ')) return <h1 key={i} className="text-2xl font-bold text-white mb-4 mt-6 border-b border-slate-700 pb-2">{line.replace('# ', '')}</h1>
                       if (line.startsWith('## ')) return <h2 key={i} className="text-xl font-semibold text-cyan-400 mb-3 mt-6">{line.replace('## ', '')}</h2>
                       if (line.startsWith('### ')) return <h3 key={i} className="text-lg font-semibold text-indigo-300 mb-2 mt-4">{line.replace('### ', '')}</h3>
                       if (line.startsWith('- ')) return <li key={i} className="ml-4 text-slate-300 mb-1">{line.replace('- ', '')}</li>
                       return <p key={i} className="text-slate-300 mb-3 leading-relaxed">{line}</p>
                    })}
                 </div>
              </div>

              {/* Citations / Sources */}
              {report.sources.length > 0 && (
                <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                   <h3 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-4 flex items-center gap-2">
                     <FileText className="w-4 h-4" />
                     References & Published Papers
                   </h3>
                   <div className="grid grid-cols-1 gap-3">
                      {report.sources.map((source, idx) => (
                        <a 
                          key={idx} 
                          href={source.url} 
                          target="_blank" 
                          rel="noopener noreferrer"
                          className="flex items-center justify-between p-3 rounded-lg bg-slate-800/50 hover:bg-slate-800 transition-all group"
                        >
                           <span className="text-sm text-slate-300 font-medium truncate pr-4">{source.title}</span>
                           <ExternalLink className="w-4 h-4 text-slate-500 group-hover:text-cyan-400" />
                        </a>
                      ))}
                   </div>
                </div>
              )}

            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ReportPage;